name: Netflix App
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps: 
        - name: checkout code
          run: actions/checkout@v3

        - name: Set up SSH
            run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan
